### ISSUE TITLE
Yii2 Admin Module

### ISSUE THREAD

**Issue by dungphanxuan** [bariew/yii2-module-cms-module#1]
Hello, Please give solution with my project.
I want to make app with yii2 basic app. In that, i create admin module. Now i want run app with some scenario example
1. Run app -> type admin ->if  Check is not login ->Show login admin form (not default yii2 basic app login)
2. 

How can you give me some solution on config or another ....
Thanks!

**Comment by bariew** [comment]
Hello! I'm sorry but I can't understand what you need. If you want to use module params you may define Module::$params property. Maybe you should ask your question on http://stackoverflow.com
